Return-Path: <linux-kselftest-owner@vger.kernel.org>
X-Original-To: lists+linux-kselftest@lfdr.de
Delivered-To: lists+linux-kselftest@lfdr.de
Received: from out1.vger.email (out1.vger.email [IPv6:2620:137:e000::1:20])
	by mail.lfdr.de (Postfix) with ESMTP id 7B5FB6953E2
	for <lists+linux-kselftest@lfdr.de>; Mon, 13 Feb 2023 23:30:47 +0100 (CET)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S229560AbjBMWaq (ORCPT <rfc822;lists+linux-kselftest@lfdr.de>);
        Mon, 13 Feb 2023 17:30:46 -0500
Received: from lindbergh.monkeyblade.net ([23.128.96.19]:40800 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S229951AbjBMWap (ORCPT
        <rfc822;linux-kselftest@vger.kernel.org>);
        Mon, 13 Feb 2023 17:30:45 -0500
Received: from mail-io1-xd2a.google.com (mail-io1-xd2a.google.com [IPv6:2607:f8b0:4864:20::d2a])
        by lindbergh.monkeyblade.net (Postfix) with ESMTPS id 82BE81D93F
        for <linux-kselftest@vger.kernel.org>; Mon, 13 Feb 2023 14:30:44 -0800 (PST)
Received: by mail-io1-xd2a.google.com with SMTP id l128so5089851iof.2
        for <linux-kselftest@vger.kernel.org>; Mon, 13 Feb 2023 14:30:44 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=linuxfoundation.org; s=google; t=1676327444;
        h=content-transfer-encoding:mime-version:message-id:date:subject:cc
         :to:from:from:to:cc:subject:date:message-id:reply-to;
        bh=wx7rLgjo31q4aRFngZaMZvvBuOkUVt0KZOQkB/G6VhE=;
        b=UGnugubJQHiQKh1fUKagWN0eCSxWHJnX1T8ppG3v25k5W1wMi/U77Ogm6zUSYdIMwE
         JVZNqI6rULxN82YJIiKRYDlwSvs6NkCloq5/pDRHZBeDIGy3zk5h8wSSFKE+tC/SccLk
         0obqZDHv4o+sPYpR53NnvVTYPtVg27RrHas80=
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20210112; t=1676327444;
        h=content-transfer-encoding:mime-version:message-id:date:subject:cc
         :to:from:x-gm-message-state:from:to:cc:subject:date:message-id
         :reply-to;
        bh=wx7rLgjo31q4aRFngZaMZvvBuOkUVt0KZOQkB/G6VhE=;
        b=PdbpY2NSrOwRsRoBkQUVVsyV9qgFiYGhb3HSs9xgyNlzrBzyfMLuoMbhn+9NjxRjL7
         kie7RsHNUEQNNvD0qA4pahgWxZHcB5oTM7ldHA5//+zlZ3G1Id/EaOTKjaqZfLqxBtQx
         +0v7MOOVEALEvfnVZ+m2Jl9fKCASnc0BuO0pAnLFmiAHLK5cdxxejISB6yQhcFW0amY8
         s/FDM1RINaSMlw6JeZsdG74psJ6Ely/+bNgO1LbYtMF6EH6QfGAkdQlLDK8u2gD4j7g0
         s9VOxPGHgxcI41WxrLeVofdzutikMNa401AQ+f/Yl26hOF08J352PnBVkrbMMl+KrmBh
         A+ug==
X-Gm-Message-State: AO0yUKXc3ow5/2b9gWr0I7qn4qCMxYoxaOl1w/QcvHUesapIKQjwuoUi
        iqjJXAZ7Ei4H2TvmDe4PtcNuIw==
X-Google-Smtp-Source: AK7set/qkONysWSWunirShm5nK5En++rvYEyBksmNjPhTvo9bFHNmDs1uU4A4iFH2F8UniVDWrIz3g==
X-Received: by 2002:a6b:3bd8:0:b0:72c:f57a:a37b with SMTP id i207-20020a6b3bd8000000b0072cf57aa37bmr85672ioa.2.1676327443835;
        Mon, 13 Feb 2023 14:30:43 -0800 (PST)
Received: from shuah-tx13.internal ([38.15.45.1])
        by smtp.gmail.com with ESMTPSA id n17-20020a056638121100b003a9515b47ebsm4341806jas.68.2023.02.13.14.30.42
        (version=TLS1_3 cipher=TLS_AES_256_GCM_SHA384 bits=256/256);
        Mon, 13 Feb 2023 14:30:43 -0800 (PST)
From:   Shuah Khan <skhan@linuxfoundation.org>
To:     shuah@kernel.org, brauner@kernel.org, sforshee@kernel.org
Cc:     Shuah Khan <skhan@linuxfoundation.org>,
        linux-fsdevel@vger.kernel.org, linux-kselftest@vger.kernel.org,
        linux-kernel@vger.kernel.org
Subject: [PATCH] selftests/mount_setattr: fix to make run_tests failure
Date:   Mon, 13 Feb 2023 15:30:41 -0700
Message-Id: <20230213223041.242089-1-skhan@linuxfoundation.org>
X-Mailer: git-send-email 2.34.1
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit
X-Spam-Status: No, score=-2.1 required=5.0 tests=BAYES_00,DKIMWL_WL_HIGH,
        DKIM_SIGNED,DKIM_VALID,DKIM_VALID_AU,DKIM_VALID_EF,RCVD_IN_DNSWL_NONE,
        SPF_HELO_NONE,SPF_PASS autolearn=ham autolearn_force=no version=3.4.6
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on
        lindbergh.monkeyblade.net
Precedence: bulk
List-ID: <linux-kselftest.vger.kernel.org>
X-Mailing-List: linux-kselftest@vger.kernel.org

make run_tests doesn't run the test. Fix Makefile to set TEST_GEN_PROGS
instead of TEST_GEN_FILES to fix the problem.

run_tests runs TEST_GEN_PROGS, TEST_CUSTOM_PROGS, and TEST_PROGS.
TEST_GEN_FILES is for files generated by tests.

Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>
---
 tools/testing/selftests/mount_setattr/Makefile | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/tools/testing/selftests/mount_setattr/Makefile b/tools/testing/selftests/mount_setattr/Makefile
index fde72df01b11..0c0d7b1234c1 100644
--- a/tools/testing/selftests/mount_setattr/Makefile
+++ b/tools/testing/selftests/mount_setattr/Makefile
@@ -2,6 +2,6 @@
 # Makefile for mount selftests.
 CFLAGS = -g $(KHDR_INCLUDES) -Wall -O2 -pthread
 
-TEST_GEN_FILES += mount_setattr_test
+TEST_GEN_PROGS := mount_setattr_test
 
 include ../lib.mk
-- 
2.37.2

